name: example-alpacaxander

services:
  example-api:
    build: ./example-backend
    env_file:
      - path: ./example-backend/.env.development
        required: true # default
      - path: ./example-backend/.env.local
        required: false
    ports:
      - "8080:8080"

  example-ui:
    build: ./example-frontend
    volumes:
      - ./example-frontend/src:/src
    ports:
      - "3000:3000"
