name: example-alpacaxander

services:
  example-api:
    build: ./example-data
    ports:
      - "8080:8080"

  example-ui:
    build: ./example-frontend
    volumes:
      - ./example-frontend/src:/src
    ports:
      - "3000:3000"
