name: Example GitHub Actions CI for example frontend
on: [pull_request]

defaults:
  run:
    shell: bash
    working-directory: ./example-frontend

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.8]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run install
        run: npm install
      - name: Run eslint
        run: npm run lint

  Build:
    name: Build production docker image
    needs: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.8]
    steps:
      - uses: actions/checkout@v4
      - name: Build production docker image
        run: npm run build:production:docker
