name: Example GitHub Actions CI for backend
run-name:
on: [pull_request]

defaults:
  run:
    shell: bash
    working-directory: ./example-backend

jobs:
  Build:
    name: Build production docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.8]
    steps:
      - uses: actions/checkout@v4
      - name: Build production docker image
        run: docker buildx build -f Dockerfile.production .
